{
	"version": 1575450665,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-2.1.1.min.js",
		"offlineClient.js",
		"images/personagemhitbox-sheet0.png",
		"images/chão.png",
		"images/personagemimagem-sheet0.png",
		"images/personagemimagem-sheet1.png",
		"images/hphud.png",
		"images/1hud-sheet0.png",
		"images/2hud-sheet0.png",
		"images/3hud-sheet0.png",
		"images/bala-sheet0.png",
		"images/bala-sheet1.png",
		"images/bala-sheet2.png",
		"images/bg.png",
		"images/planta1-sheet0.png",
		"images/planta2-sheet0.png",
		"images/planta2-sheet1.png",
		"images/planta3-sheet0.png",
		"images/spawnplantas-sheet0.png",
		"images/bgg-sheet0.png",
		"images/limite-sheet0.png",
		"images/arma-sheet0.png",
		"media/atira dxabo.ogg",
		"media/dxabo.ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png"
	]
}